version: '3'
services:
  node:
    image: node:18.16.0
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "npm i && npm run dev"

  frontend:
    image: node:18.16.0
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: >
      bash -c "npm i && npm run dev"
    ports:
      - 5173:5173
    depends_on:
      - node
    environment:
      - VITE_API_URL=http://node:3000

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mariadb_data:/var/lib/mysql

  redis:
    image: redis
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
